# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004 as base

FROM base as download

ARG JFROG_CLI_VERSION=2.50.2
ARG JFROG_CLI_URL_AMD64="https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.50.2/jfrog-cli-linux-amd64/jf"
ARG JFROG_CLI_SHA256_AMD64="e033c79dbdd60538df1b0b5fb139c8bc5698fbdf86024b2a41620c31eedab1d2"
ARG JFROG_CLI_URL_ARM64="https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.50.2/jfrog-cli-linux-arm64/jf"
ARG JFROG_CLI_SHA256_ARM64="d64c92e74cad6fa7fa5deb70a1c511bd37005cf8d2fa1ded6605d4c7cd19041c"
ARG JFROG_CLI_URL_ARMHF="https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.50.2/jfrog-cli-linux-arm/jf"
ARG JFROG_CLI_SHA256_ARMHF="a3bf926edb350dc52a20391496816212147720f9a15edae9c773b2e0fc64a249"

WORKDIR /download

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl

  arch="$(arch)"
  echo "arch=${arch}"
  case "${arch##*-}" in \
    x86_64) \
      JFROG_CLI_URL="${JFROG_CLI_URL_AMD64}" \
      JFROG_CLI_SHA256="${JFROG_CLI_SHA256_AMD64}" \
      ;; \
    aarch64) \
      JFROG_CLI_URL="${JFROG_CLI_URL_ARM64}" \
      JFROG_CLI_SHA256="${JFROG_CLI_SHA256_ARM64}" \
      ;; \
    armv7l) \
      JFROG_CLI_URL="${JFROG_CLI_URL_ARMHF}" \
      JFROG_CLI_SHA256="${JFROG_CLI_SHA256_ARMHF}" \
      ;; \
  esac
  curl -fsSL -o jf ${JFROG_CLI_URL}
  echo "${JFROG_CLI_SHA256} jf" | sha256sum -c -
EOF

FROM base

COPY --from=download --chmod=755 /download/jf /usr/local/bin/jf

ARG JFROG_USER=jfrog
ARG JFROG_GROUP=jfrog
ARG JFROG_UID=1000
ARG JFROG_GID=1000
ARG JFROG_HOME=/home/jfrog

RUN <<EOF
  groupadd -r $JFROG_GROUP --gid=$JFROG_GID
  useradd -g $JFROG_GID --create-home --home-dir=$JFROG_HOME --shell=/bin/bash $JFROG_USER
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq

  rm /var/log/dpkg.log
  rm -rf /var/lib/apt/lists/*
EOF

USER $JFROG_USER
WORKDIR $JFROG_HOME

ENTRYPOINT ["/usr/local/bin/jf"]
