# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20240427 as base

FROM base as download

ARG JFROG_CLI_VERSION
ARG JFROG_CLI_URL_AMD64
ARG JFROG_CLI_SHA256_AMD64
ARG JFROG_CLI_URL_ARM64
ARG JFROG_CLI_SHA256_ARM64
ARG JFROG_CLI_URL_ARMHF
ARG JFROG_CLI_SHA256_ARMHF

WORKDIR /download

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl

  arch="$(arch)"
  echo "arch=${arch}"
  case "${arch##*-}" in \
    x86_64) \
      JFROG_CLI_URL="${JFROG_CLI_URL_AMD64}" \
      JFROG_CLI_SHA256="${JFROG_CLI_SHA256_AMD64}" \
      ;; \
    aarch64) \
      JFROG_CLI_URL="${JFROG_CLI_URL_ARM64}" \
      JFROG_CLI_SHA256="${JFROG_CLI_SHA256_ARM64}" \
      ;; \
    armv7l) \
      JFROG_CLI_URL="${JFROG_CLI_URL_ARMHF}" \
      JFROG_CLI_SHA256="${JFROG_CLI_SHA256_ARMHF}" \
      ;; \
  esac
  curl -fsSL -o jf ${JFROG_CLI_URL}
  echo "${JFROG_CLI_SHA256} jf" | sha256sum -c -
EOF

FROM base

COPY --from=download --chmod=755 /download/jf /usr/local/bin/jf

ARG JFROG_USER=jfrog
ARG JFROG_GROUP=jfrog
ARG JFROG_UID=1000
ARG JFROG_GID=1000
ARG JFROG_HOME=/home/jfrog

RUN <<EOF
  groupadd -r $JFROG_GROUP --gid=$JFROG_GID
  useradd -g $JFROG_GID --create-home --home-dir=$JFROG_HOME --shell=/bin/bash $JFROG_USER
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq

  rm /var/log/dpkg.log
  rm -rf /var/lib/apt/lists/*
EOF

USER $JFROG_USER
WORKDIR $JFROG_HOME

ENTRYPOINT ["/usr/local/bin/jf"]
