# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308 as builder

WORKDIR /tmp
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      CINC_URL='http://downloads.cinc.sh/files/stable/cinc/18.1.0/ubuntu/22.04/cinc_18.1.0-1_amd64.deb' \
      CINC_SHA256='af8a54c875661bcc5a3ac640912b80ed033b90eeb4ccbe7d3ed6f520491c7587' \
      ;; \
    arm64) \
      CINC_URL='http://downloads.cinc.sh/files/stable/cinc/18.1.0/ubuntu/22.04/cinc_18.1.0-1_arm64.deb' \
      CINC_SHA256='f66be4d18f5bf23511dc57b676a73ba3f820651ce9f1b26b1ad00fd931d760f9' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o cinc.deb ${CINC_URL}
  echo "${CINC_SHA256} cinc.deb" | sha256sum -c -
EOF

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

LABEL \
    org.opencontainers.image.source="https://github.com/boxcutter/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Cinc Client is an automation platform built from Chef Infra"


COPY --from=builder /tmp/cinc.deb /tmp/cinc.deb

RUN <<EOF
  apt-get update \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates
  dpkg -i /tmp/cinc.deb
  rm -rf /var/lib/apt/lists/*
EOF
    
VOLUME ["/opt/cinc"]
