# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:focal-20220801 as build

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  mkdir -p /tmp/meshcmd
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      MESHCMD_URL='https://alt.meshcentral.com/meshagents?meshcmd=6' \
      ;; \
    arm64) \
      MESHCMD_URL='https://alt.meshcentral.com/meshagents?meshcmd=26' \
      ;; \
    armhf) \
      MESHCMD_URL='https://alt.meshcentral.com/meshagents?meshcmd=25' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac
  curl -o /tmp/meshcmd/meshcmd "$MESHCMD_URL"
EOF

FROM $CONTAINER_REGISTRY/ubuntu:focal-20220531

WORKDIR /opt/meshcmd/bin

COPY --from=build --chmod=755 /tmp/meshcmd /opt/meshcmd/bin

ENV PATH "/opt/meshcmd/bin:${PATH}"
