# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308 as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    unzip
  mkdir -p /tmp/terraform
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in
  amd64)
    TERRAFORM_URL='https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip'
    TERRAFORM_SHA256='9f3ca33d04f5335472829d1df7785115b60176d610ae6f1583343b0a2221a931'
    ;;
  arm64)
    TERRAFORM_URL='https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_arm64.zip'
    TERRAFORM_SHA256='39c182670c4e63e918e0a16080b1cc47bb16e158d7da96333d682d6a9cb8eb91'
    ;;
  armhf)
    TERRAFORM_URL='https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_arm.zip'
    TERRAFORM_SHA256='dbb1e7179279bd739ff889b994738f25a80a8eac5ae255b50bdf5f86b9eda28b'
    ;;
  *)
    echo "unsupported architecture"
    exit 1
    ;;
  esac
  curl -fsSL -o /tmp/terraform.zip ${TERRAFORM_URL}
  echo "${TERRAFORM_SHA256} /tmp/terraform.zip" | sha256sum -c - 
  unzip /tmp/terraform.zip -d /tmp/terraform/
EOF

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    ca-certificates \
    curl \
    git \
    openssh-client
  apt-get clean
  apt-get -y autoremove
  rm -rf /var/lib/apt/lists/*
EOF

COPY --from=build /tmp/terraform/terraform /opt/hashicorp/terraform/bin/terraform

WORKDIR /terraform
ENV PATH "/opt/hashicorp/terraform/bin:${PATH}"

ENTRYPOINT ["/opt/hashicorp/terraform/bin/terraform"]
