# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20240808
FROM $BASE_IMAGE AS base

FROM base AS download

ARG TERRAFORM_URL_AMD64
ARG TERRAFORM_SHA256_AMD64
ARG TERRAFORM_URL_ARM64
ARG TERRAFORM_SHA256_ARM64

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    unzip
  mkdir -p /tmp/terraform
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in
  amd64)
    TERRAFORM_URL="${TERRAFORM_URL_AMD64}"
    TERRAFORM_SHA256="${TERRAFORM_SHA256_AMD64}"
    ;;
  arm64)
    TERRAFORM_URL="${TERRAFORM_URL_ARM64}"
    TERRAFORM_SHA256="${TERRAFORM_SHA256_ARM64}"
    ;;
  *)
    echo "unsupported architecture"
    exit 1
    ;;
  esac
  curl -fsSL -o /tmp/terraform.zip ${TERRAFORM_URL}
  echo "${TERRAFORM_SHA256} /tmp/terraform.zip" | sha256sum -c - 
  unzip /tmp/terraform.zip -d /tmp/terraform/
EOF

FROM base

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    ca-certificates \
    curl \
    git \
    openssh-client
  apt-get clean
  apt-get -y autoremove
  rm -rf /var/lib/apt/lists/*
EOF

COPY --from=download /tmp/terraform/terraform /opt/hashicorp/terraform/bin/terraform

WORKDIR /terraform
ENV PATH="/opt/hashicorp/terraform/bin:${PATH}"

ENTRYPOINT ["/opt/hashicorp/terraform/bin/terraform"]
