# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:focal-20221019 as builder

WORKDIR /tmp
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      CINC_URL='http://downloads.cinc.sh/files/stable/cinc/17.10.0/ubuntu/20.04/cinc_17.10.0-1_amd64.deb' \
      CINC_SHA256='79f3b62e1768f1deb0c505fc44fa5c180b0298605fcf3f6baafa0bb962924d12' \
      ;; \
    arm64) \
      CINC_URL='http://downloads.cinc.sh/files/stable/cinc/17.10.0/ubuntu/20.04/cinc_17.10.0-1_arm64.deb' \
      CINC_SHA256='3df81ab25896e5fc1dde929864fe77bf96d053071f268e1b23cc3d44907e389e' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o cinc.deb ${CINC_URL}
  echo "${CINC_SHA256} cinc.deb" | sha256sum -c -
EOF

FROM $CONTAINER_REGISTRY/ubuntu:focal-20221019

LABEL \
    org.opencontainers.image.source="https://github.com/boxcutter/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Cinc Client is an automation platform built from Chef Infra"


COPY --from=builder /tmp/cinc.deb /tmp/cinc.deb

RUN <<EOF
  apt-get update \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates
  dpkg -i /tmp/cinc.deb
EOF
    
VOLUME ["/opt/cinc"]
