# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/debian:11
FROM $BASE_IMAGE AS base

ENV DEBIAN_FRONTEND noninteractive

# hadolint ignore=DL3041
RUN /usr/bin/apt-get update && \
  /usr/bin/apt-get -y install \
  apt-transport-https \
  apt-utils \
  cron \
  curl \
  dbus \
  dirmngr \
  dmidecode \
  gnupg \
  ifupdown \
  iptables \
  iputils-ping \
  kmod \
  less \
  locales \
  lsb-release \
  lsof \
  net-tools \
  netcat \
  nmap \
  perl \
  procps \
  strace \
  sudo \
  systemd \
  tcpdump \
  telnet \
  tzdata \
  udev \
  vim-tiny \
  wget && \
  /usr/bin/apt-get clean && \
  /usr/bin/apt-get -y autoremove && \
  rm -rf /tmp/* /var/tmp/* && \
  ln -s /bin/mkdir /usr/bin/mkdir && \
  # Don't start any optional services.
  find /etc/systemd/system \
  /lib/systemd/system \
  -path '*.wants/*' \
  \( -name '*getty*' \
  -or -name '*apt-daily*' \
  -or -name '*systemd-timesyncd*' \
  -or -name '*systemd-logind*' \
  -or -name '*systemd-vconsole-setup*' \
  -or -name '*systemd-readahead*' \
  -or -name '*udev*' \) \
  -exec rm -v {} \; && \
  systemctl set-default multi-user.target && \
  systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service

CMD [ "/bin/systemd" ]
