# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20240808
FROM $BASE_IMAGE AS base

FROM base as download

ARG PORTAINER_URL_AMD64
ARG PORTAINER_SHA256_AMD64
ARG PORTAINER_URL_ARM64
ARG PORTAINER_SHA256_ARM64

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      PORTAINER_URL="${PORTAINER_URL_AMD64}" \
      PORTAINER_SHA256="${PORTAINER_SHA256_AMD64}" \
      ;; \
    arm64) \
      PORTAINER_URL="${PORTAINER_URL_ARM64}" \
      PORTAINER_SHA256="${PORTAINER_SHA256_ARM64}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/portainer.tar.gz ${PORTAINER_URL}
  echo "${PORTAINER_SHA256} /tmp/portainer.tar.gz" | sha256sum -c -
  mkdir -p /tmp/portainer
  tar xvf /tmp/portainer.tar.gz -C /tmp
EOF

FROM base

COPY --from=download /tmp/portainer/docker /
COPY --from=download /tmp/portainer/docker-compose /
COPY --from=download /tmp/portainer/helm /
COPY --from=download /tmp/portainer/kubectl /
COPY --from=download /tmp/portainer/mustache-templates /mustache-templates/
COPY --from=download /tmp/portainer/portainer /
COPY --from=download /tmp/portainer/public /public/

RUN <<EOF
  apt-get update -y
  apt-get install -y --no-install-recommends \
    ca-certificates
  rm -rf /var/lib/apt/lists/*
EOF

VOLUME /data
WORKDIR /

EXPOSE 9000
EXPOSE 9443
EXPOSE 8000

ENTRYPOINT ["/portainer"]
