# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308 as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      PORTAINER_URL='https://github.com/portainer/portainer/releases/download/2.17.1/portainer-2.17.1-linux-amd64.tar.gz' \
      PORTAINER_SHA256='ec1a1a7e53481b1e4b19f45249fd7398f390d52646ac740d90f254a3b6a5a096' \
      ;; \
    arm64) \
      PORTAINER_URL='https://github.com/portainer/portainer/releases/download/2.17.1/portainer-2.17.1-linux-arm64.tar.gz' \
      PORTAINER_SHA256='aaa3841d6e590c5b6820bbe3f2f36f32530e7ce7ef0dd91ee1ce73001c51e2f1' \
      ;; \
    armhf) \
      PORTAINER_URL='https://github.com/portainer/portainer/releases/download/2.17.1/portainer-2.17.1-linux-arm.tar.gz' \
      PORTAINER_SHA256='aaa3841d6e590c5b6820bbe3f2f36f32530e7ce7ef0dd91ee1ce73001c51e2f1' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/portainer.tar.gz ${PORTAINER_URL}
  echo "${PORTAINER_SHA256} /tmp/portainer.tar.gz" | sha256sum -c -
  mkdir -p /tmp/portainer
  tar xvf /tmp/portainer.tar.gz -C /tmp
EOF

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Zlib" \
    org.opencontainers.image.description="Docker container management made simple, with the world’s most popular GUI-based container management platform." \
    org.opencontainers.image.vendor="Portainer.io"

COPY --from=build /tmp/portainer/docker /
COPY --from=build /tmp/portainer/docker-compose /
COPY --from=build /tmp/portainer/helm /
COPY --from=build /tmp/portainer/kubectl /
COPY --from=build /tmp/portainer/mustache-templates /mustache-templates/
COPY --from=build /tmp/portainer/portainer /
COPY --from=build /tmp/portainer/public /public/

RUN <<EOF
  apt-get update -y
  apt-get install -y --no-install-recommends \
    ca-certificates
  rm -rf /var/lib/apt/lists/*
EOF

VOLUME /data
WORKDIR /

EXPOSE 9000
EXPOSE 9443
EXPOSE 8000

ENTRYPOINT ["/portainer"]
