# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004 as base

FROM base as download

ARG PORTAINER_URL_AMD64="https://github.com/portainer/portainer/releases/download/2.17.1/portainer-2.17.1-linux-amd64.tar.gz"
ARG PORTAINER_SHA256_AMD64="ec1a1a7e53481b1e4b19f45249fd7398f390d52646ac740d90f254a3b6a5a096"
ARG PORTAINER_URL_ARM64="https://github.com/portainer/portainer/releases/download/2.17.1/portainer-2.17.1-linux-arm64.tar.gz"
ARG PORTAINER_SHA256_ARM64="aaa3841d6e590c5b6820bbe3f2f36f32530e7ce7ef0dd91ee1ce73001c51e2f1"
ARG PORTAINER_URL_ARMHF="https://github.com/portainer/portainer/releases/download/2.17.1/portainer-2.17.1-linux-arm.tar.gz"
ARG PORTAINER_SHA256_ARMHF="aaa3841d6e590c5b6820bbe3f2f36f32530e7ce7ef0dd91ee1ce73001c51e2f1"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      PORTAINER_URL="${PORTAINER_URL_AMD64}" \
      PORTAINER_SHA256="${PORTAINER_SHA256_AMD64}" \
      ;; \
    arm64) \
      PORTAINER_URL="${PORTAINER_URL_ARM64}" \
      PORTAINER_SHA256="${PORTAINER_SHA256_ARM64}" \
      ;; \
    armhf) \
      PORTAINER_URL="${PORTAINER_URL_ARMHF}" \
      PORTAINER_SHA256="${PORTAINER_SHA256_ARMHF}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/portainer.tar.gz ${PORTAINER_URL}
  echo "${PORTAINER_SHA256} /tmp/portainer.tar.gz" | sha256sum -c -
  mkdir -p /tmp/portainer
  tar xvf /tmp/portainer.tar.gz -C /tmp
EOF

FROM base

COPY --from=download /tmp/portainer/docker /
COPY --from=download /tmp/portainer/docker-compose /
COPY --from=download /tmp/portainer/helm /
COPY --from=download /tmp/portainer/kubectl /
COPY --from=download /tmp/portainer/mustache-templates /mustache-templates/
COPY --from=download /tmp/portainer/portainer /
COPY --from=download /tmp/portainer/public /public/

RUN <<EOF
  apt-get update -y
  apt-get install -y --no-install-recommends \
    ca-certificates
  rm -rf /var/lib/apt/lists/*
EOF

VOLUME /data
WORKDIR /

EXPOSE 9000
EXPOSE 9443
EXPOSE 8000

ENTRYPOINT ["/portainer"]
