ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004 AS base

ARG COLLECTD_EXPORTER_URL_AMD64="https://github.com/prometheus/collectd_exporter/releases/download/v0.5.0/collectd_exporter-0.5.0.linux-amd64.tar.gz"
ARG COLLECTD_EXPORTER_SHA256_AMD64="5b906b1ea49c119024350c10b4b8491857a20336a0ffd778a3f10d7536a6d123"
ARG COLLECTD_EXPORTER_URL_ARM64="https://github.com/prometheus/collectd_exporter/releases/download/v0.5.0/collectd_exporter-0.5.0.linux-arm64.tar.gz"
ARG COLLECTD_EXPORTER_SHA256_ARM64="eef28573acb3410137640e80787784027858831bfd8502c5c43df4ca6dc34d45"
ARG COLLECTD_EXPORTER_URL_ARMHF="https://github.com/prometheus/collectd_exporter/releases/download/v0.5.0/collectd_exporter-0.5.0.linux-armv7.tar.gz"
ARG COLLECTD_EXPORTER_SHA256_ARMHF="53cea60cd356f76ac3b67a9f0246ffe4a0c43ea5cca2f0d88f944e32a6494cfd"

FROM base as download

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/collectd_exporter \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      COLLECTD_EXPORTER_URL="$COLLECTD_EXPORTER_URL_AMD64" \
      COLLECTD_EXPORTER_SHA256="$COLLECTD_EXPORTER_SHA256_AMD64" \
      ;; \
    arm64) \
      COLLECTD_EXPORTER_URL="$COLLECTD_EXPORTER_URL_ARM64" \
      COLLECTD_EXPORTER_SHA256="$COLLECTD_EXPORTER_SHA256_ARM64" \
      ;; \
    armhf) \
      COLLECTD_EXPORTER_URL="$COLLECTD_EXPORTER_URL_ARMHF" \
      COLLECTD_EXPORTER_SHA256="$COLLECTD_EXPORTER_SHA256_ARMHF" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/collectd_exporter.tar.gz ${COLLECTD_EXPORTER_URL} \
  && echo "${COLLECTD_EXPORTER_SHA256} /tmp/collectd_exporter.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/collectd_exporter.tar.gz --strip-components 1 -C /tmp/collectd_exporter

FROM base

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --chmod=755 --from=download /tmp/collectd_exporter/collectd_exporter /usr/local/bin/collectd_exporter

EXPOSE 9103
USER nobody
ENTRYPOINT [ "/usr/local/bin/collectd_exporter" ]
