# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20240808
FROM $BASE_IMAGE AS base

ARG COLLECTD_EXPORTER_URL_AMD64
ARG COLLECTD_EXPORTER_SHA256_AMD64
ARG COLLECTD_EXPORTER_URL_ARM64
ARG COLLECTD_EXPORTER_SHA256_ARM64
ARG COLLECTD_EXPORTER_URL_ARMHF
ARG COLLECTD_EXPORTER_SHA256_ARMHF

FROM base as download

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/collectd_exporter \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      COLLECTD_EXPORTER_URL="$COLLECTD_EXPORTER_URL_AMD64" \
      COLLECTD_EXPORTER_SHA256="$COLLECTD_EXPORTER_SHA256_AMD64" \
      ;; \
    arm64) \
      COLLECTD_EXPORTER_URL="$COLLECTD_EXPORTER_URL_ARM64" \
      COLLECTD_EXPORTER_SHA256="$COLLECTD_EXPORTER_SHA256_ARM64" \
      ;; \
    armhf) \
      COLLECTD_EXPORTER_URL="$COLLECTD_EXPORTER_URL_ARMHF" \
      COLLECTD_EXPORTER_SHA256="$COLLECTD_EXPORTER_SHA256_ARMHF" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/collectd_exporter.tar.gz ${COLLECTD_EXPORTER_URL} \
  && echo "${COLLECTD_EXPORTER_SHA256} /tmp/collectd_exporter.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/collectd_exporter.tar.gz --strip-components 1 -C /tmp/collectd_exporter

FROM base

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --chmod=755 --from=download /tmp/collectd_exporter/collectd_exporter /usr/local/bin/collectd_exporter

EXPOSE 9103
USER nobody
ENTRYPOINT [ "/usr/local/bin/collectd_exporter" ]
