ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004

# Create user and set ownership and permissions as required
RUN useradd -m ldap

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    ldap-utils \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*

USER ldap
