ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0"

# Create user and set ownership and permissions as required
# RUN useradd -m ldap

# RUN apt-get update -y \
#   && apt-get install -y --no-install-recommends \
#     ca-certificates \
#     ldap-utils \
#   && apt-get autoremove -y \
#   && rm -rf /var/lib/apt/lists/*

# USER ldap

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y tzdata ca-certificates nginx smokeping curl spawn-fcgi supervisor \
    && apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# ENV TZ=Asia/Taipei
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY supervisord-smokeping.conf /etc/supervisor/conf.d/smokeping.conf
COPY supervisord-fcgi.conf /etc/supervisor/conf.d/fcgi.conf
COPY supervisord-nginx.conf /etc/supervisor/conf.d/nginx.conf
COPY nginx.conf /etc/nginx/sites-available/default

RUN mkdir -p /var/run/smokeping /var/lib/smokeping/__cgi/Local/
RUN chown -R smokeping:www-data /var/run/smokeping /var/lib/smokeping
RUN chmod -R 777 /var/cache/smokeping /var/lib/smokeping
RUN mv /usr/share/smokeping/www/smokeping.fcgi.dist /usr/share/smokeping/www/smokeping.fcgi

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
