ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 AS build

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Cinc Auditing and Testing Framework."

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      CINC_AUDITOR_URL='http://downloads.cinc.sh/files/stable/cinc-auditor/5.14.0/ubuntu/20.04/cinc-auditor_5.14.0-1_amd64.deb' \
      ;; \
    arm64) \
      CINC_AUDITOR_URL='http://downloads.cinc.sh/files/stable/cinc-auditor/5.14.0/ubuntu/20.04/cinc-auditor_5.14.0-1_arm64.deb' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/cinc-auditor.deb ${CINC_AUDITOR_URL}

FROM ubuntu:20.04

ENV PATH=/opt/cinc-auditor/bin:/opt/cinc-auditor/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Run the entire container with the default locale to be en_US.UTF-8
RUN apt-get update && \
    apt-get install -y --no-install-recommends locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

WORKDIR /share

COPY --from=build /tmp/cinc-auditor.deb  /tmp/cinc-auditor.deb

RUN apt-get update && \
    apt-get install -y --no-install-recommends /tmp/cinc-auditor.deb && \
    rm -rf /tmp/cinc-auditor.deb.rpm

# Install any packages that make life easier for an InSpec installation
RUN apt-get install -y --no-install-recommends git

ENTRYPOINT ["cinc-auditor"]
CMD ["help"]
VOLUME ["/share"]
