# syntax=docker/dockerfile:1.3
ARG BUILD_CONTAINER_REGISTRY=docker.io
ARG CONTAINER_REGISTRY=docker.io/polymathrobotics
FROM $BUILD_CONTAINER_REGISTRY/ubuntu:20.04 as build

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Pulumi CLI container for python."

ARG PULUMI_VERSION=3.30.0
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl

# Install the Pulumi SDK, including the CLI and language runtimes.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL https://get.pulumi.com/ | bash -s -- --version $PULUMI_VERSION

# The runtime container
# This is our base container, so let's copy all the runtimes to .pulumi/bin
FROM $CONTAINER_REGISTRY/python-arm64:3.8-focal

WORKDIR /pulumi/projects

RUN --mount=type=cache,target=/var/lib/apt/list \
    --mount=type=cache,target=/var/cache/apt \
    apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    git

# Uses the workdir, copies from pulumi interim container
COPY --from=build /root/.pulumi/bin/pulumi /pulumi/bin/pulumi
COPY --from=build /root/.pulumi/bin/*-python* /pulumi/bin/

ENV PATH "/pulumi/bin:${PATH}"
CMD ["pulumi"]