ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/polymathrobotics/python:3.9-jammy

ARG FLAKE8_VERSION=5.0.4
WORKDIR /code
RUN python3 -m pip install --no-cache-dir flake8==$FLAKE8_VERSION

ENTRYPOINT ["flake8"]
CMD ["--help"]
