ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004 as builder

WORKDIR /tmp

ARG LEGO_URL_AMD64="https://github.com/go-acme/lego/releases/download/v4.13.3/lego_v4.13.3_linux_amd64.tar.gz"
ARG LEGO_SHA256_AMD64="d321fc3ee7f33337d8e2c64c6e807a2526c1f1310a40aad3641b06ee60526d95"
ARG LEGO_URL_ARM64="https://github.com/go-acme/lego/releases/download/v4.13.3/lego_v4.13.3_linux_arm64.tar.gz"
ARG LEGO_SHA256_ARM64="787d11f03046285e1e800e8ac19382c05f28d6933236c52fafe025f7cadd9a0b"
ARG LEGO_URL_ARMHF="https://github.com/go-acme/lego/releases/download/v4.13.3/lego_v4.13.3_linux_armv7.tar.gz"
ARG LEGO_SHA256_ARMHF="4ad6255765052a949f4fc68e24aa34c9ec4f720e4b0f49e968ef682eb5263e70"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      LEGO_URL="$LEGO_URL_AMD64" \
      LEGO_SHA256="$LEGO_SHA256_AMD64" \
      ;; \
    arm64) \
      LEGO_URL="$LEGO_URL_ARM64" \
      LEGO_SHA256="$LEGO_SHA256_AMD64" \
      ;; \
    armhf) \
      LEGO_URL="$LEGO_URL_ARMHF" \
      LEGO_SHA256="$LEGO_SHA256_ARMHF" \
      ;; \
    esac
    curl -fsSL -o lego.tar.gz ${LEGO_URL}
    echo "${LEGO_SHA256} lego.tar.gz" | sha256sum -c -
    mkdir -p lego
    tar --extract \
        --file lego.tar.gz \
        --directory /tmp/lego
EOF

FROM builder

RUN <<EOF
  apt-get update -y
  apt-get install -y --no-install-recommends \
    ca-certificates
  apt-get autoremove -y
  rm -rf /var/lib/apt/lists/*
EOF

WORKDIR /opt
COPY --from=builder /tmp/lego/ /opt/lego

RUN ln -s /opt/lego/lego /usr/local/bin/lego

ENTRYPOINT ["lego"]
