# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20240808
FROM $BASE_IMAGE AS base

FROM base AS download

WORKDIR /tmp

ARG LEGO_URL_AMD64
ARG LEGO_SHA256_AMD64
ARG LEGO_URL_ARM64
ARG LEGO_SHA256_ARM64
ARG LEGO_URL_ARMHF
ARG LEGO_SHA256_ARMHF

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      LEGO_URL="$LEGO_URL_AMD64" \
      LEGO_SHA256="$LEGO_SHA256_AMD64" \
      ;; \
    arm64) \
      LEGO_URL="$LEGO_URL_ARM64" \
      LEGO_SHA256="$LEGO_SHA256_AMD64" \
      ;; \
    armhf) \
      LEGO_URL="$LEGO_URL_ARMHF" \
      LEGO_SHA256="$LEGO_SHA256_ARMHF" \
      ;; \
    esac
    curl -fsSL -o lego.tar.gz ${LEGO_URL}
    echo "${LEGO_SHA256} lego.tar.gz" | sha256sum -c -
    mkdir -p lego
    tar --extract \
        --file lego.tar.gz \
        --directory /tmp/lego
EOF

FROM base

RUN <<EOF
  apt-get update -y
  apt-get install -y --no-install-recommends \
    ca-certificates
  apt-get autoremove -y
  rm -rf /var/lib/apt/lists/*
EOF

WORKDIR /opt
COPY --from=download /tmp/lego/ /opt/lego

RUN ln -s /opt/lego/lego /usr/local/bin/lego

ENTRYPOINT ["lego"]
