ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 as build

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0"

ADD https://github.com/TomWright/dasel/releases/download/v1.24.1/dasel_linux_arm64 /tmp/dasel

FROM $CONTAINER_REGISTRY/ubuntu:20.04

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    jq \
  && rm -rf /var/lib/apt/lists/*

COPY --chmod=755 --from=build /tmp/dasel /usr/local/bin/dasel

WORKDIR /share

ENTRYPOINT ["/usr/local/bin/dasel"]
CMD ["--help"]
VOLUME ["/share"]
