# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/polymathrobotics/ros:humble-ros-base-jammy
FROM ${BASE_IMAGE}

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    python3-dev \
    python3-rosinstall \
    openssh-client \
    iputils-ping \
    ros-humble-rmw-cyclonedds-cpp \
    nano \
    curl \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install pip from source
RUN /usr/bin/curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" \
    && /usr/bin/python3 get-pip.py \
    && /usr/local/bin/pip3 install --no-cache-dir --upgrade --force-reinstall setuptools==58.2.0 \
    && /bin/rm get-pip.py \
    && /bin/rm -rf ~/.cache/pip

CMD ["/bin/bash"]
