# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20240808
FROM $BASE_IMAGE AS base

ARG CLI_URL_AMD64

FROM base AS download

WORKDIR /tmp/pspace

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    unzip
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      CLI_URL="${CLI_URL_AMD64}" \
      ;; \
    arm64) \
      echo "Error: Official builds for Linux aarch64 are not yet available." \
      exit 1 \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/pspace.zip "${CLI_URL}"
  unzip /tmp/pspace.zip -d /tmp/pspace
EOF

WORKDIR /app

FROM base

COPY --from=download /tmp/pspace/pspace /usr/local/bin/pspace

ENTRYPOINT ["/usr/local/bin/pspace"]
