# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Paperspace command-line interface."

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    unzip
  rm -rf /var/lib/apt/lists/*
EOF

ARG USERNAME=paperspace
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV HOME /home/$USERNAME

RUN <<EOF
  groupadd --gid "$USER_GID" "$USERNAME"
  useradd --uid "$USER_UID" --gid "$USER_GID" -m "$USERNAME"
EOF

USER $USERNAME
WORKDIR $HOME

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  curl -fsSL https://paperspace.com/install.sh | sh
EOF

WORKDIR $HOME
ENV PAPERSPACE_INSTALL="/home/paperspace/.paperspace"
ENV PATH="$PAPERPERSPACE_INSTALL/bin:$PATH"
ENTRYPOINT ["/home/paperspace/.paperspace/bin/pspace"]
