# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231211.1

ARG CERTBOT_VERSION

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update -y
  apt-get install -y --no-install-recommends \
    python3 \
    python3-venv \
    libaugeas0
  apt-get autoremove -y
  rm -rf /var/lib/apt/lists/*
EOF

RUN python3 -m venv /opt/certbot/ \
  && /opt/certbot/bin/pip install --upgrade pip \
  && /opt/certbot/bin/pip install certbot==$CERTBOT_VERSION \
  && /opt/certbot/bin/pip install certbot-dns-cloudflare==$CERTBOT_VERSION

RUN ln -s /opt/certbot/bin/certbot /usr/local/bin/certbot

VOLUME /etc/letsencrypt /var/lib/letsencrypt

ENTRYPOINT [ "certbot" ]

