ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:22.04

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="A container image for testing with Ubuntu 22.04."

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    apt-transport-https \
    apt-utils \
    curl \
    dbus \
    cron \
    dirmngr \
    dmidecode \
    gnupg \
    iproute2 \
    iptables \
    iputils-ping \
    kmod \
    less \
    linux-base \
    locales \
    lsb-release \
    lsof \
    net-tools \
    netcat \
    nmap \
    perl \
    procps \
    snapd \
    strace \
    sudo \
    systemd \
    tcpdump \
    telnet \
    tzdata \
    udev \
    vim-tiny \
    wget \
  && apt-get clean \
  && apt-get -y autoremove \
  && rm -rf /tmp/* /var/tmp/* \
  # Don't start any optional services
  && find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    \( -name '*getty*' \
    -or -name '*apt-daily*' \
    -or -name '*systemd-timesyncd*' \
    -or -name '*systemd-logind*' \
    -or -name '*systemd-vconsole-setup*' \
    -or -name '*systemd-readahead*' \
    -or -name '*udev*' \) \
    -exec rm -v \{\} \; \
  && systemctl set-default multi-user.target \
  && systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service

CMD [ "/bin/systemd" ]
