ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 as build

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Prometheus monitoring system and time series database in a docker image."

ARG PROMETHEUS_URL=https://github.com/prometheus/prometheus/releases/download/v2.34.0/prometheus-2.34.0.linux-arm64.tar.gz
ARG PROMETHEUS_SHA256=f00255293a801b34003e0ad1d34bb89827bbfd1bba286c39575884aac84a6058

# Making use of ADD curl auto-download capability for now
# hadolint ignore=DL3020
ADD $PROMETHEUS_URL /tmp/prometheus.tar.gz

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/prometheus \
  && echo "${PROMETHEUS_SHA256} /tmp/prometheus.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/prometheus.tar.gz -C /tmp/prometheus --strip-components 1

FROM $CONTAINER_REGISTRY/ubuntu:20.04

WORKDIR /prometheus

COPY --chmod=755 --from=build /tmp/prometheus/prometheus /usr/local/bin/prometheus
COPY --chmod=755 --from=build /tmp/prometheus/promtool /usr/local/bin/promtool
COPY --from=build /tmp/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
COPY --from=build /tmp/prometheus/console_libraries/ /usr/share/prometheus/console_libraries/
COPY --from=build /tmp/prometheus/consoles/ /usr/share/prometheus/consoles/
COPY --from=build /tmp/prometheus/LICENSE /LICENSE
COPY --from=build /tmp/prometheus/NOTICE /NOTICE

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && ln -s /usr/share/prometheus/console_libraries /usr/share/prometheus/consoles/ /etc/prometheus/ \
  && chown -R nobody:nogroup /etc/prometheus /prometheus

USER nobody
EXPOSE 9090
VOLUME ["/prometheus"]
ENTRYPOINT ["/usr/local/bin/prometheus"]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--storage.tsdb.retention.time=15d", \
             "--web.console.libraries=/usr/share/prometheus/console_libraries", \
             "--web.console.templates=/usr/share/prometheus/consoles" ]
