ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 as build

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Prometheus node exporter for machine metrics, in a Docker container image."

ARG NODE_EXPORTER_VERSION=1.3.1
ARG NODE_EXPORTER_URL=https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-arm64.tar.gz
ARG NODE_EXPORTER_SHA256=f19f35175f87d41545fa7d4657e834e3a37c1fe69f3bf56bc031a256117764e7

# Making use of ADD curl capability for now
# hadolint ignore=DL3020
ADD $NODE_EXPORTER_URL /tmp/node_exporter.tar.gz

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/node_exporter \
  && echo "${NODE_EXPORTER_SHA256} /tmp/node_exporter.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/node_exporter.tar.gz -C /tmp/node_exporter --strip-components 1

FROM $CONTAINER_REGISTRY/ubuntu:20.04

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --chmod=755 --from=build /tmp/node_exporter/node_exporter /usr/local/bin/node_exporter

EXPOSE 9100
ENTRYPOINT [ "/usr/local/bin/node_exporter" ]
