# syntax=docker/dockerfile:1
ARG UBUNTU_DISTRO=rolling
ARG UBUNTU_DISTRO_VERSION=0.12.0-1
ARG BASE_IMAGE=docker.io/ubuntu:${UBUNTU_DISTRO}-${UBUNTU_DISTRO_VERSION}
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS base

FROM base AS download

ARG RAW_GITHUBUSERCONTENT_BASE_URL

# download gpg key
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  curl -sSL "${RAW_GITHUBUSERCONTENT_BASE_URL}/ros/rosdistro/master/ros.key" \
    -o /usr/share/keyrings/ros2-latest-archive-keyring.gpg
EOF

FROM base AS ready

ARG UBUNTU_DISTRO
ARG ROS_PACKAGES_URI
ARG ROSDISTRO_PKGS_SYNC_DATE

COPY --from=download /usr/share/keyrings/ros2-latest-archive-keyring.gpg /usr/share/keyrings/ros2-latest-archive-keyring.gpg

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    && rm -rf /var/lib/apt/lists/*

# setup sources.list
RUN echo "deb [ signed-by=/usr/share/keyrings/ros2-latest-archive-keyring.gpg ] ${ROS_PACKAGES_URI} ${UBUNTU_DISTRO} main" > /etc/apt/sources.list.d/ros2-latest.list

# setup environment
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

ENV ROSDISTRO_PKGS_SYNC_DATE=$ROSDISTRO_PKGS_SYNC_DATE

FROM ready AS builder

ARG RAW_GITHUBUSERCONTENT_BASE_URL

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    ros-dev-tools \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# setup colcon mixin and metadata
ENV COLCON_HOME=/etc/colcon
RUN colcon mixin add default \
      "${RAW_GITHUBUSERCONTENT_BASE_URL}/colcon/colcon-mixin-repository/master/index.yaml" && \
    colcon mixin update && \
    colcon metadata add default \
      "${RAW_GITHUBUSERCONTENT_BASE_URL}/colcon/colcon-metadata-repository/master/index.yaml" && \
    colcon metadata update

# bootstrap rosdep
# NOTE: this is the first step that actually differentiates on ROS distribution
ARG ROS_DISTRO
ENV ROS_DISTRO=${ROS_DISTRO}
RUN rosdep init && rosdep update --rosdistro "${ROS_DISTRO}"
COPY gather-rosdeps.sh /usr/local/bin/gather-rosdeps
