# syntax=docker/dockerfile:1
# GitHub doesn't offer older versions of the cli in their package repo, so use releases from GitHub
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20240808
FROM $BASE_IMAGE AS base

ARG GITHUB_CLI_URL_AMD64
ARG GITHUB_CLI_SHA256_AMD64
ARG GITHUB_CLI_URL_ARM64
ARG GITHUB_CLI_SHA256_ARM64
ARG GITHUB_CLI_URL_ARMHF
ARG GITHUB_CLI_SHA256_ARMHF

FROM base AS download

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      GITHUB_CLI_URL="$GITHUB_CLI_URL_AMD64" \
      GITHUB_CLI_SHA256="$GITHUB_CLI_SHA256_AMD64" \
      ;; \
    arm64) \
      GITHUB_CLI_URL="$GITHUB_CLI_URL_ARM64" \
      GITHUB_CLI_SHA256="$GITHUB_CLI_SHA256_ARM64" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/gh.deb "${GITHUB_CLI_URL}"
  echo "${GITHUB_CLI_SHA256} /tmp/gh.deb" | sha256sum -c -
EOF

FROM base

ARG USERNAME=gh
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV HOME=/home/$USERNAME

COPY --from=download /tmp/gh.deb /tmp/gh.deb

RUN <<EOF
  groupadd --gid "$USER_GID" "$USERNAME"
  useradd --uid "$USER_UID" --gid "$USER_GID" -m "$USERNAME"
  mkdir -p "/home/$USERNAME/.config"
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    jq \
    openssh-client
  dpkg -i /tmp/gh.deb
  rm -rf /var/lib/apt/lists/*
EOF

VOLUME ["/share"]
WORKDIR /share

USER $USERNAME
ENTRYPOINT ["gh"]
CMD ["--help"]
