# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20250126
FROM $BASE_IMAGE AS download

ARG SHFMT_URL_AMD64
ARG SHFMT_SHA256_AMD64
ARG SHFMT_URL_ARM64
ARG SHFMT_SHA256_ARM64

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      SHFMT_URL="${SHFMT_URL_AMD64}" \
      SHFMT_SHA256="${SHFMT_SHA256_AMD64}" \
      ;; \
    arm64) \
      SHFMT_URL="${SHFMT_URL_ARM64}" \
      SHFMT_SHA256="${SHFMT_SHA256_ARM64}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/shfmt ${SHFMT_URL}
  echo "${SHFMT_SHA256} /tmp/shfmt" | sha256sum -c -
EOF

FROM scratch

COPY --from=download --chmod=777 /tmp/shfmt /usr/local/bin/shfmt

WORKDIR /share
ENTRYPOINT ["/usr/local/bin/shfmt"]
CMD ["-h"]
