ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230425 as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/alertmanager \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      ALERTMANAGER_URL='https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-amd64.tar.gz' \
      ALERTMANAGER_SHA256='206cf787c01921574ca171220bb9b48b043c3ad6e744017030fed586eb48e04b' \
      ;; \
    arm64) \
      ALERTMANAGER_URL='https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-arm64.tar.gz' \
      ALERTMANAGER_SHA256='20db5e4e12bcce8e2e419cc4c2bc35062ddbc14d2aacb77e4d5684c0eab7f0fe' \
      ;; \
    armhf) \
      ALERTMANAGER_URL='https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-armv7.tar.gz' \
      ALERTMANAGER_SHA256='3cfd839d4463a7679d32800258b11471498ebc49483273d588818c0432a80af1' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/alertmanager.tar.gz ${ALERTMANAGER_URL} \
  && echo "${ALERTMANAGER_SHA256} /tmp/alertmanager.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/alertmanager.tar.gz --strip-components 1 -C /tmp/alertmanager

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230425

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Prometheus Alermanager."

WORKDIR /alertmanager

COPY --chmod=755 --from=build /tmp/alertmanager/amtool /usr/local/bin/amtool
COPY --chmod=755 --from=build /tmp/alertmanager/alertmanager /usr/local/bin/alertmanager
COPY --from=build /tmp/alertmanager/alertmanager.yml /etc/alertmanager/alertmanager.yml

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && chown -R nobody:nogroup /etc/alertmanager /alertmanager

USER nobody
EXPOSE 9093
VOLUME [ "/alertmanager" ]
ENTRYPOINT [ "/usr/local/bin/alertmanager" ]
CMD [ "--config.file=/etc/alertmanager/alertmanager.yml", \
      "--storage.path=/alertmanager" ]
