# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:noble-20250404
FROM $BASE_IMAGE AS base

FROM base AS download

ARG DOCTL_URL_AMD64
ARG DOCTL_SHA256_AMD64
ARG DOCTL_URL_ARM64
ARG DOCTL_SHA256_ARM64

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      DOCTL_URL="$DOCTL_URL_AMD64" \
      DOCTL_SHA256="$DOCTL_SHA256_AMD64" \
      ;; \
    arm64) \
      DOCTL_URL="$DOCTL_URL_ARM64" \
      DOCTL_SHA256="$DOCTL_SHA256_ARM64" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/doctl.tar.gz ${DOCTL_URL}
  echo "${DOCTL_SHA256} /tmp/doctl.tar.gz" | sha256sum -c -
  mkdir -p /tmp/doctl
  tar xvf /tmp/doctl.tar.gz -C /tmp/doctl
EOF

FROM base

RUN <<EOF
  apt-get update -y
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    openssh-client
  apt-get autoremove -y
  rm -rf /var/lib/apt/lists/*
EOF

WORKDIR /app
COPY --from=download /tmp/doctl/doctl /usr/local/bin/doctl

ENTRYPOINT ["/usr/local/bin/doctl"]
