# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:focal-20221130 as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      DOCTL_URL='https://github.com/digitalocean/doctl/releases/download/v1.92.0/doctl-1.92.0-linux-amd64.tar.gz' \
      DOCTL_SHA256='c1b10106ca0df325bd597ac222c7dfca563e644200227718d15e161d72ac7c92'
      ;; \
    arm64) \
      DOCTL_URL='https://github.com/digitalocean/doctl/releases/download/v1.92.0/doctl-1.92.0-linux-arm64.tar.gz'
      DOCTL_SHA256='bad0922e40ffd29805b0e3844d6fdfe8a07e939b7a2652f1df9886f93b646cb8'
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/doctl.tar.gz ${DOCTL_URL}
  echo "${DOCTL_SHA256} /tmp/doctl.tar.gz" | sha256sum -c -
  mkdir -p /tmp/doctl
  tar xvf /tmp/doctl.tar.gz -C /tmp/doctl
EOF

FROM $CONTAINER_REGISTRY/ubuntu:focal-20221130

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Digital Ocean command-line interface."

RUN <<EOF
  apt-get update -y
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    openssh-client
  apt-get autoremove -y
  rm -rf /var/lib/apt/lists/*
EOF

WORKDIR /app
COPY --from=build /tmp/doctl/doctl /usr/local/bin/doctl

ENTRYPOINT ["/usr/local/bin/doctl"]
