ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/polymathrobotics/python:3.9-jammy

ARG BLACK_VERSION
WORKDIR /code
RUN python3 -m pip install --no-cache-dir black==$BLACK_VERSION

ENTRYPOINT  ["black"]
