# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/polymathrobotics/python:3.9-jammy
FROM $BASE_IMAGE

ARG BLACK_VERSION
WORKDIR /code
RUN python3 -m pip install --no-cache-dir black==$BLACK_VERSION

ENTRYPOINT  ["black"]
