# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230425
ARG S6_OVERLAY_VERSION=3.1.5.0

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="GPL-2.0" \
    org.opencontainers.image.description="Smokeping latency logging, graphing and alerting system."
  
# hadolint ignore=DL3015
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    apache2 \
    ca-certificates \
    curl \
    dnsutils \
    iputils-ping \
    smokeping \
    xz-utils
  rm -rf /var/lib/apt/lists/*
EOF

ARG TARGETPLATFORM
ARG TARGETARCH # https://github.com/casperklein/docker-smokeping/blob/master/Dockerfile

RUN <<EOF
  mkdir -p /var/run/smokeping
  chown smokeping:root /var/run/smokeping
  a2enmod rewrite
  sed -i 's|</VirtualHost>|RewriteEngine On\nRewriteRule ^/$ /smokeping/ [R=301]\n</VirtualHost>|' /etc/apache2/sites-available/000-default.conf

  curl \
    --silent \
    --show-error \
    --output-dir /tmp \
    --location \
    --remote-name \
    https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz
  tar --directory / --xz --extract --file /tmp/s6-overlay-noarch.tar.xz
  case ${TARGETARCH} in \
    "amd64") S6_OVERLAY_ARCH=x86_64 ;; \
    "arm64") S6_OVERLAY_ARCH=aarch64 ;; \
    "arm/v7") S6_OVERLAY_ARCH=armhf ;; \
  esac
  curl \
    --silent \
    --show-error \
    --output-dir /tmp \
    --location \
    --remote-name \
    https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_OVERLAY_ARCH}.tar.xz
  tar --directory / --xz --extract --file /tmp/s6-overlay-${S6_OVERLAY_ARCH}.tar.xz
  rm -rf /var/lib/apt/lists/*
EOF

COPY etc/ /etc

ENTRYPOINT ["/init"]
