# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230425
ARG S6_OVERLAY_VERSION=3.1.5.0
ENV S6_KEEP_ENV 1 # Don't reset the environment on /init so we get TZ

ENV TZ=Etc/UTC

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="GPL-2.0" \
    org.opencontainers.image.description="Smokeping latency logging, graphing and alerting system."
  
# hadolint ignore=DL3015
RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    apache2 \
    ca-certificates \
    curl \
    dnsutils \
    iputils-ping \
    openssh-client \
    smokeping \
    tzdata \
    xz-utils
  rm -rf /var/lib/apt/lists/*
EOF

ARG TARGETPLATFORM
ARG TARGETARCH # https://github.com/casperklein/docker-smokeping/blob/master/Dockerfile

RUN <<EOF
  mkdir -p /var/run/smokeping
  chown smokeping:root /var/run/smokeping
  a2enmod rewrite
  sed -i 's|</VirtualHost>|RewriteEngine On\nRewriteRule ^/$ /smokeping/ [R=301]\n</VirtualHost>|' /etc/apache2/sites-available/000-default.conf

  curl \
    --silent \
    --show-error \
    --output-dir /tmp \
    --location \
    --remote-name \
    https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz
  tar --directory / --xz --extract --file /tmp/s6-overlay-noarch.tar.xz
  case ${TARGETARCH} in \
    "amd64") \
      mkdir -p /tmp/echoping
      curl --output-dir /tmp/echoping -LO http://archive.ubuntu.com/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_amd64.deb
      curl --output-dir /tmp/echoping -LO http://archive.ubuntu.com/ubuntu/pool/main/p/popt/libpopt0_1.16-14_amd64.deb
      curl --output-dir /tmp/echoping -LO http://archive.ubuntu.com/ubuntu/pool/universe/e/echoping/echoping_6.0.2-10ubuntu1_amd64.deb
      dpkg -i /tmp/echoping/libidn11_1.33-2.2ubuntu2_amd64.deb
      dpkg -i /tmp/echoping/libpopt0_1.16-14_amd64.deb
      dpkg -i /tmp/echoping/echoping_6.0.2-10ubuntu1_amd64.deb
      S6_OVERLAY_ARCH=x86_64 ;; \
    "arm64") \
      mkdir -p /tmp/echoping
      curl --output-dir /tmp/echoping -LO http://ports.ubuntu.com/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_arm64.deb
      curl --output-dir /tmp/echoping -LO http://ports.ubuntu.com/pool/main/p/popt/libpopt0_1.16-14_arm64.deb
      curl --output-dir /tmp/echoping -LO http://ports.ubuntu.com/pool/universe/e/echoping/echoping_6.0.2-10ubuntu1_arm64.deb
      dpkg -i /tmp/echoping/libidn11_1.33-2.2ubuntu2_arm64.deb
      dpkg -i /tmp/echoping/libpopt0_1.16-14_arm64.deb
      dpkg -i /tmp/echoping/echoping_6.0.2-10ubuntu1_arm64.deb
      S6_OVERLAY_ARCH=aarch64 ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl \
    --silent \
    --show-error \
    --output-dir /tmp \
    --location \
    --remote-name \
    https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_OVERLAY_ARCH}.tar.xz
  tar --directory / --xz --extract --file /tmp/s6-overlay-${S6_OVERLAY_ARCH}.tar.xz
  rm -rf /var/lib/apt/lists/*
EOF

COPY etc/ /etc
EXPOSE 80

ENTRYPOINT ["/init"]
