# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:focal-20221130 AS build

ARG OP_CLI_VERSION=2.12.0

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    unzip
  gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  mkdir -p /tmp/build
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      OP_CLI_URL="https://cache.agilebits.com/dist/1P/op2/pkg/v${OP_CLI_VERSION}/op_linux_amd64_v${OP_CLI_VERSION}.zip"
      ;; \
    arm64) \
      OP_CLI_URL="https://cache.agilebits.com/dist/1P/op2/pkg/v${OP_CLI_VERSION}/op_linux_arm64_v${OP_CLI_VERSION}.zip"
      ;; \
    armhf) \
      OP_CLI_URL="https://cache.agilebits.com/dist/1P/op2/pkg/v${OP_CLI_VERSION}/op_linux_arm_v${OP_CLI_VERSION}.zip"
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/op_linux.zip ${OP_CLI_URL}
  unzip -d /tmp/build /tmp/op_linux.zip
  cp /tmp/build/op /usr/local/bin/op
  gpg --verify /tmp/build/op.sig /usr/local/bin/op
  # tiny smoke test to ensure the binary we downloaded runs
  op --version
EOF

FROM $CONTAINER_REGISTRY/ubuntu:focal-20221130

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="1Password command-line interface."

RUN <<EOF
  groupadd -g 999 opuser
  useradd -r -u 999 -g opuser opuser
  mkdir -p /home/opuser
  chown -R opuser /home/opuser
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    parallel \
    jq
  rm -rf /var/lib/apt/lists/*
EOF

COPY --from=build /usr/local/bin/op /usr/local/bin/op

USER opuser
WORKDIR /home/opuser

CMD ["/bin/bash"]
