# syntax=docker/dockerfile:1
# Arguments used in FROM need to be defined before the first build stage
ARG BASE_IMAGE=docker.io/polymathrobotics/python:3.9-noble
# hadolint ignore=DL3006
FROM $BASE_IMAGE

# Install depthai
RUN pip install --no-cache-dir depthai

# Copy your script into the image
COPY list_devices.py /list_devices.py

# Default entrypoint
CMD ["python3", "/list_devices.py"]
