# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/polymathrobotics/ruby:3.1-slim-jammy
FROM $BASE_IMAGE

ARG MDL_VERSION

RUN gem install mdl --no-document -v $MDL_VERSION

RUN useradd -ms /sbin/nologin  mdl

USER mdl

WORKDIR  /data

ENTRYPOINT ["mdl"]
CMD ["--help"]
