FROM ubuntu:20.04 AS build

ARG SHELLCHECK_VERSION=v0.8.0

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    xz-utils \
  && curl -sSLO https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.aarch64.tar.xz \
  && tar -xf shellcheck-${SHELLCHECK_VERSION}.linux.aarch64.tar.xz --wildcards '*/shellcheck' --strip-components=1

FROM scratch
COPY --from=build /shellcheck /usr/local/bin/shellcheck

CMD ["shellcheck"]
