# syntax=docker/dockerfile:1
ARG BUILD_IMAGE=docker.io/polymathrobotics/golang:1.23-jammy
FROM ${BUILD_IMAGE} AS build

WORKDIR /usr/src

RUN git clone https://github.com/facebookincubator/go2chef.git

WORKDIR /usr/src/go2chef

RUN <<EOF
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      mkdir -p build/linux
      GOARCH=amd64 go build -o build/linux/go2chef ./bin
      ;; \
    arm64) \
      mkdir -p build/linux
      GOARCH=arm64 go build -o build/linux/go2chef ./bin
      ;;
  esac
EOF

FROM docker.io/ubuntu:jammy-20240808
COPY --from=build --chmod=777 /usr/src/go2chef/build/linux/go2chef /usr/local/bin/go2chef
