ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 as build

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Select, put and delete data from JSON, TOML, YAML, XML and CSV files with a single tool."

ADD https://github.com/TomWright/dasel/releases/download/v1.24.1/dasel_linux_amd64 /tmp/dasel

FROM $CONTAINER_REGISTRY/ubuntu:20.04

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    jq \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      DASEL_URL=https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_amd64 \
      ;; \
    arm64) \
      DASEL_URL=https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_arm64 \
      ;; \
    armhf) \
      DASEL_URL=https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_arm32 \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/dasel -L ${DASEL_URL} \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir -p /share

COPY --chmod=755 --from=build /tmp/dasel /usr/local/bin/dasel

ENTRYPOINT ["/usr/local/bin/dasel"]
CMD ["--help"]
VOLUME ["/share"]
WORKDIR /share
