# syntax=docker/dockerfile:1.3-labs

ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:focal-20220531 as build

ARG LLVM_TAG
ENV LLVM_TAG ${LLVM_TAG:-llvmorg-14.0.4}

RUN <<EOF
  set -eu
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    clang \
    cmake \
    git \
    lld \
    llvm \
    ninja-build \
    python3 
  rm -rf /var/lib/apt/lists/*
EOF

WORKDIR /build
RUN git clone --depth 1 --branch ${LLVM_TAG} https://github.com/llvm/llvm-project.git

WORKDIR /build/llvm-project/llvm/build
RUN <<EOF
  cmake \
    -G Ninja \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
    ..
  ninja clang-tidy
EOF

FROM $CONTAINER_REGISTRY/ubuntu:focal-20220531

LABEL org.opencontainers.image.source=https://github.com/taylorific/dockerfile

WORKDIR /src

COPY --from=build /build/llvm-project/llvm/build/bin/clang-tidy /usr/local/bin

ENTRYPOINT ["clang-tidy"]
CMD ["--help"]
