ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308 as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/grafana \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      GRAFANA_URL='https://dl.grafana.com/oss/release/grafana-9.4.3.linux-amd64.tar.gz' \
      GRAFANA_SHA256='6aaebfb0c7d855e6f1878ebecf1a617d6b6d14de2f06952008b5e86cb595a339' \
      ;; \
    arm64) \
      GRAFANA_URL='https://dl.grafana.com/oss/release/grafana-9.4.3.linux-arm64.tar.gz' \
      GRAFANA_SHA256='2c18bfee509dfc474df709c405b24cd8d847ff4a726927c40454d7e3bc4bd45c' \
      ;; \
    armhf) \
      GRAFANA_URL='https://dl.grafana.com/oss/release/grafana-9.4.3.linux-armv7.tar.gz' \
      GRAFANA_SHA256='f1003e88d6d57ec12998ee6dbc13d73015f78734dbe9e9cb63d3b273c6c0f14d' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/grafana.tar.gz ${GRAFANA_URL} \
  && echo "${GRAFANA_SHA256} /tmp/grafana.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/grafana.tar.gz -C /tmp/grafana --strip-components 1

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Grafana - the open observability platform in a container image."

ARG GF_UID="472"
ARG GF_GID="0"

ENV PATH=/usr/share/grafana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    GF_PATHS_CONFIG="/etc/grafana/grafana.ini" \
    GF_PATHS_DATA="/var/lib/grafana" \
    GF_PATHS_HOME="/usr/share/grafana" \
    GF_PATHS_LOGS="/var/log/grafana" \
    GF_PATHS_PLUGINS="/var/lib/grafana/plugins" \
    GF_PATHS_PROVISIONING="/etc/grafana/provisioning"

WORKDIR $GF_PATHS_HOME

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    tzdata \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=build /tmp/grafana "$GF_PATHS_HOME"

# Group names won't have spaces in them
# hadolint ignore=SC2046
RUN if [ ! $(getent group "$GF_GID") ]; then \
      addgroup --system --gid $GF_GID grafana; \
    fi

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# hadolint ignore=SC2155
RUN export GF_GID_NAME=$(getent group $GF_GID | cut -d':' -f1) && \
    mkdir -p "$GF_PATHS_HOME/.aws" && \
    adduser --system --uid $GF_UID --ingroup "$GF_GID_NAME" grafana && \
    mkdir -p "$GF_PATHS_PROVISIONING/datasources" \
             "$GF_PATHS_PROVISIONING/dashboards" \
             "$GF_PATHS_PROVISIONING/notifiers" \
             "$GF_PATHS_PROVISIONING/plugins" \
             "$GF_PATHS_PROVISIONING/access-control" \
             "$GF_PATHS_LOGS" \
             "$GF_PATHS_PLUGINS" \
             "$GF_PATHS_DATA" && \
    cp "$GF_PATHS_HOME/conf/sample.ini" "$GF_PATHS_CONFIG" && \
    cp "$GF_PATHS_HOME/conf/ldap.toml" /etc/grafana/ldap.toml && \
    chown -R "grafana:$GF_GID_NAME" "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING" && \
    chmod -R 777 "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"

COPY --chmod=755 ./run.sh /run.sh

EXPOSE 3000
USER "$GF_UID"
ENTRYPOINT [ "/run.sh" ]
