ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004 as base

FROM base as download

ARG GRAFANA_URL_AMD64="https://dl.grafana.com/oss/release/grafana-9.5.1.linux-amd64.tar.gz"
ARG GRAFANA_SHA256_AMD64="d9b7505cdd4299c1835c36547ffe2e62d3b0ec7600dca2c644a0519572c9c387"
ARG GRAFANA_URL_ARM64="https://dl.grafana.com/oss/release/grafana-9.5.1.linux-arm64.tar.gz"
ARG GRAFANA_SHA256_ARM64="ed6c692be378e2d9a1a730169867ea4f3da83d814f123a1a340579644032c93e"
ARG GRAFANA_URL_ARMHF="https://dl.grafana.com/oss/release/grafana-9.5.1.linux-armv7.tar.gz"
ARG GRAFANA_SHA256_ARMHF="29dfd878e78b5810d3bfd2399e5b0a159e38220f9283c44c202299b8e59ab099"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/grafana \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      GRAFANA_URL="${GRAFANA_URL_AMD64}" \
      GRAFANA_SHA256="${GRAFANA_SHA256_AMD64}" \
      ;; \
    arm64) \
      GRAFANA_URL="${GRAFANA_URL_ARM64}" \
      GRAFANA_SHA256="${GRAFANA_SHA256_ARM64}" \
      ;; \
    armhf) \
      GRAFANA_URL="${GRAFANA_URL_ARMHF}" \
      GRAFANA_SHA256="${GRAFANA_SHA256_ARMHF}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/grafana.tar.gz ${GRAFANA_URL} \
  && echo "${GRAFANA_SHA256} /tmp/grafana.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/grafana.tar.gz -C /tmp/grafana --strip-components 1

FROM base

ARG GF_UID="472"
ARG GF_GID="0"

ENV PATH=/usr/share/grafana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    GF_PATHS_CONFIG="/etc/grafana/grafana.ini" \
    GF_PATHS_DATA="/var/lib/grafana" \
    GF_PATHS_HOME="/usr/share/grafana" \
    GF_PATHS_LOGS="/var/log/grafana" \
    GF_PATHS_PLUGINS="/var/lib/grafana/plugins" \
    GF_PATHS_PROVISIONING="/etc/grafana/provisioning"

WORKDIR $GF_PATHS_HOME

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    tzdata \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*

COPY --from=download /tmp/grafana "$GF_PATHS_HOME"

# Group names won't have spaces in them
# hadolint ignore=SC2046
RUN if [ ! $(getent group "$GF_GID") ]; then \
      addgroup --system --gid $GF_GID grafana; \
    fi

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# hadolint ignore=SC2155
RUN export GF_GID_NAME=$(getent group $GF_GID | cut -d':' -f1) && \
    mkdir -p "$GF_PATHS_HOME/.aws" && \
    adduser --system --uid $GF_UID --ingroup "$GF_GID_NAME" grafana && \
    mkdir -p "$GF_PATHS_PROVISIONING/datasources" \
             "$GF_PATHS_PROVISIONING/dashboards" \
             "$GF_PATHS_PROVISIONING/notifiers" \
             "$GF_PATHS_PROVISIONING/plugins" \
             "$GF_PATHS_PROVISIONING/access-control" \
             "$GF_PATHS_LOGS" \
             "$GF_PATHS_PLUGINS" \
             "$GF_PATHS_DATA" && \
    cp "$GF_PATHS_HOME/conf/sample.ini" "$GF_PATHS_CONFIG" && \
    cp "$GF_PATHS_HOME/conf/ldap.toml" /etc/grafana/ldap.toml && \
    chown -R "grafana:$GF_GID_NAME" "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING" && \
    chmod -R 777 "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"

COPY --chmod=755 ./run.sh /run.sh

EXPOSE 3000
USER "$GF_UID"
ENTRYPOINT [ "/run.sh" ]
