ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/boxcutter/python:3.11-jammy as build

ARG CERTBOT_VERSION=1.27.0

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

RUN python3 -m venv /opt/certbot/ \
  && /opt/certbot/bin/pip install certbot==$CERTBOT_VERSION

FROM $CONTAINER_REGISTRY/boxcutter/python:3.11-jammy

COPY --from=build /opt/certbot /opt/certbot

RUN ln -s /opt/certbot/bin/certbot /usr/local/bin/certbot

VOLUME /etc/letsencrypt /var/lib/letsencrypt

ENTRYPOINT [ "certbot" ]

