ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 as build

LABEL \
  org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.description="Cinc Infra"

ARG CINC_URL=http://downloads.cinc.sh/files/stable/cinc/17.10.0/ubuntu/20.04/cinc_17.10.0-1_amd64.deb

# Making use of ADD curl download capability for now
# hadolint ignore=DL3020
ADD $CINC_URL /tmp/cinc.deb

FROM $CONTAINER_REGISTRY/ubuntu:20.04

COPY --from=build /tmp/cinc.deb  /tmp/cinc.deb

RUN --mount=type=cache,target=/var/lib/apt/list \
    --mount=type=cache,target=/var/cache/apt \
  apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && dpkg -i /tmp/cinc.deb
    
VOLUME ["/opt/cinc"]
