# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308 as builder

WORKDIR /tmp

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      CINC_WORKSTATION_URL='http://downloads.cinc.sh/files/stable/cinc-workstation/23.3.1030/ubuntu/22.04/cinc-workstation_23.3.1030-1_amd64.deb' \
      CINC_WORKSTATION_SHA256='b95c83df184cdc7af3ded5ce2a493308a2e0d8a3b7a23903012886bd2a754ea3' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o cinc-workstation.deb ${CINC_WORKSTATION_URL}
  echo "${CINC_WORKSTATION_SHA256} cinc-workstation.deb" | sha256sum -c -
EOF

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

LABEL \
  org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.description="Cinc Workstation"

# From cinc shell-init bash
ENV PATH="/opt/cinc-workstation/bin:/home/taylor/.chef/gem/ruby/3.1.0/bin:/opt/cinc-workstation/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/cinc-workstation/gitbin" \
    GEM_ROOT="/opt/cinc-workstation/embedded/lib/ruby/gems/3.1.0" \
    GEM_HOME="/root/.chef/gem/ruby/3.1.0" \
    GEM_PATH="/root/.chef/gem/ruby/3.1.0:/opt/cinc-workstation/embedded/lib/ruby/gems/3.1.0"


# Run the entire container with the default local to be en_US.UTF-8
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends locales
  locale-gen en_US.UTF-8
  update-locale LANG=en_US.UTF-8
  rm -rf /var/lib/apt/lists/*
EOF

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

COPY --from=builder /tmp/cinc-workstation.deb /tmp/cinc-workstation.deb

WORKDIR /cinc

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gcc \
    git \
    graphviz \
    make \
    rsync \
    ssh \
    vim-tiny
  dpkg -i /tmp/cinc-workstation.deb
  apt-get clean
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log*log /var/log/apt/* /var/lib/dkpg*-old /var/cache/debconf/*-old
EOF

CMD ["/bin/bash"]

