# syntax=docker/dockerfile:1.3-labs

ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:focal-20220531 as build

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  mkdir -p /tmp/actions-runner
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in
  amd64)
    ACTIONS_RUNNER_URL='https://github.com/actions/runner/releases/download/v2.293.0/actions-runner-linux-x64-2.293.0.tar.gz'
    ACTIONS_RUNNER_SHA256='06d62d551b686239a47d73e99a557d87e0e4fa62bdddcf1d74d4e6b2521f8c10'
    ;;
  arm64)
    ACTIONS_RUNNER_URL='https://github.com/actions/runner/releases/download/v2.293.0/actions-runner-linux-arm64-2.293.0.tar.gz'
    ACTIONS_RUNNER_SHA256='003fde87923900ae85d3a28f8b364936725bbd0f7eb9afeb73c40f3e117cc9c9'
    ;;
  armhf)
    ACTIONS_RUNNER_URL='https://github.com/actions/runner/releases/download/v2.293.0/actions-runner-linux-arm-2.293.0.tar.gz'
    ACTIONS_RUNNER_SHA256='7910c0cb6a908735d1a1bf2849dcae8516848aa3f6d408ed9c35a95ca4d5266b'
    ;;
  *)
    echo "unsupported architecture"
    exit 1
    ;;
  esac
  curl -fsSL -o /tmp/actions-runner.tar.gz ${ACTIONS_RUNNER_URL}
  echo "${ACTIONS_RUNNER_SHA256} /tmp/actions-runner.tar.gz" | sha256sum -c -
  tar xvf /tmp/actions-runner.tar.gz -C /tmp/actions-runner
EOF

FROM $CONTAINER_REGISTRY/ubuntu:focal-20220531

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    ca-certificates \
    curl \
    libicu-dev
  apt-get clean
  apt-get -y autoremove
  rm -rf /var/lib/apt/lists/*
EOF

RUN adduser --no-create-home runner -uid 8003

COPY --chmod=755 ./entrypoint.sh /entrypoint.sh

USER runner

WORKDIR /opt/github-actions-runner

COPY --from=build --chown=runner /tmp/actions-runner /opt/github-actions-runner
ENTRYPOINT ["/entrypoint.sh"]
