ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/polymathrobotics/node:18-jammy

ARG PAPERSPACE_CLI_VERSION=0.2.2

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    openssh-client \
    tini \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g paperspace-node@${PAPERSPACE_CLI_VERSION} && npm cache clean --force

USER node
WORKDIR /app

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["paperspace"]
