ARG CONTAINER_REGISTRY=quay.io/centos
FROM $CONTAINER_REGISTRY/centos:stream8

LABEL \
  org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.description="Cinc Infra"

ARG CINC_CLIENT_VERSION=17.10.0

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -L https://omnitruck.cinc.sh/install.sh | bash -s -- -v ${CINC_CLIENT_VERSION} \
  && dnf -y clean all \
  && rm -rf /var/cache \
  && rm -rf /var/log/*

VOLUME ["/opt/cinc"]
