ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230425 as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/prometheus \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz' \
      PROMETHEUS_SHA256='cfea92d07dfd9a9536d91dff6366d897f752b1068b9540b3e2669b0281bb8ebf' \
      ;; \
    arm64) \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-arm64.tar.gz' \
      PROMETHEUS_SHA256='79c4262a27495e5dff45a2ce85495be2394d3eecd51f0366c706f6c9c729f672' \
      ;; \
    armhf) \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-armv7.tar.gz' \
      PROMETHEUS_SHA256='2c973310a4be2792d80016102ec115800493a322c301fd51da57469374f274af' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/prometheus.tar.gz ${PROMETHEUS_URL} \
  && echo "${PROMETHEUS_SHA256} /tmp/prometheus.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/prometheus.tar.gz -C /tmp/prometheus --strip-components 1

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230425

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Prometheus monitoring system and time series database."

WORKDIR /prometheus

COPY --chmod=755 --from=build /tmp/prometheus/prometheus /usr/local/bin/prometheus
COPY --chmod=755 --from=build /tmp/prometheus/promtool /usr/local/bin/promtool
COPY --from=build /tmp/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
COPY --from=build /tmp/prometheus/console_libraries/ /usr/share/prometheus/console_libraries/
COPY --from=build /tmp/prometheus/consoles/ /usr/share/prometheus/consoles/
COPY --from=build /tmp/prometheus/LICENSE /LICENSE
COPY --from=build /tmp/prometheus/NOTICE /NOTICE

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && ln -s /usr/share/prometheus/console_libraries /usr/share/prometheus/consoles/ /etc/prometheus/ \
  && chown -R nobody:nogroup /etc/prometheus /prometheus

USER nobody
EXPOSE 9090
VOLUME ["/prometheus"]
ENTRYPOINT ["/usr/local/bin/prometheus"]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--storage.tsdb.retention.time=15d", \
             "--web.console.libraries=/usr/share/prometheus/console_libraries", \
             "--web.console.templates=/usr/share/prometheus/consoles" ]
