ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308 as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/prometheus \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.42.0/prometheus-2.42.0.linux-amd64.tar.gz' \
      PROMETHEUS_SHA256='422dab055ed9c7bcaff52b718705f9192c6fac0de6b7e78dd278e70ee2663dcc' \
      ;; \
    arm64) \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.42.0/prometheus-2.42.0.linux-arm64.tar.gz' \
      PROMETHEUS_SHA256='b947e4890d221f6b1d09c963fd0440720f2b5d08c29e190d6365f4b3d3e92a9d' \
      ;; \
    armhf) \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.42.0/prometheus-2.42.0.linux-armv7.tar.gz' \
      PROMETHEUS_SHA256='0409d72ecf92d7884274f7b19df8f7b97ad4dd32e04d9952eb7417afbc48f35f' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/prometheus.tar.gz ${PROMETHEUS_URL} \
  && echo "${PROMETHEUS_SHA256} /tmp/prometheus.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/prometheus.tar.gz -C /tmp/prometheus --strip-components 1

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Prometheus monitoring system and time series database in a docker image."

WORKDIR /prometheus

COPY --chmod=755 --from=build /tmp/prometheus/prometheus /usr/local/bin/prometheus
COPY --chmod=755 --from=build /tmp/prometheus/promtool /usr/local/bin/promtool
COPY --from=build /tmp/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
COPY --from=build /tmp/prometheus/console_libraries/ /usr/share/prometheus/console_libraries/
COPY --from=build /tmp/prometheus/consoles/ /usr/share/prometheus/consoles/
COPY --from=build /tmp/prometheus/LICENSE /LICENSE
COPY --from=build /tmp/prometheus/NOTICE /NOTICE

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && ln -s /usr/share/prometheus/console_libraries /usr/share/prometheus/consoles/ /etc/prometheus/ \
  && chown -R nobody:nogroup /etc/prometheus /prometheus

USER nobody
EXPOSE 9090
VOLUME ["/prometheus"]
ENTRYPOINT ["/usr/local/bin/prometheus"]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--storage.tsdb.retention.time=15d", \
             "--web.console.libraries=/usr/share/prometheus/console_libraries", \
             "--web.console.templates=/usr/share/prometheus/consoles" ]
