ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 as build

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Prometheus monitoring system and time series database in a docker image."

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/prometheus \
  && ARCH= \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      ARCH='amd64' \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.35.0/prometheus-2.35.0.linux-amd64.tar.gz' \
      PROMETHEUS_SHA256='e4546960688d1c85530ec3a93e109d15b540f3251e1f4736d0d9735e1e857faf' \
      ;; \
    arm64) \
      ARCH='arm64' \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.35.0/prometheus-2.35.0.linux-arm64.tar.gz' \
      PROMETHEUS_SHA256='3ebe0c533583a9ab03363a80aa629edd8e0cc42da3583e33958eb7abe74d4cd2' \
      ;; \
    armhf) \
      ARCH='armv7' \
      PROMETHEUS_URL='https://github.com/prometheus/prometheus/releases/download/v2.35.0/prometheus-2.35.0.linux-armv7.tar.gz' \
      PROMETHEUS_SHA256='a50274c833ef058502fb723806e28537ef276ec628d63e0c3fdc407ca7b65272' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/prometheus.tar.gz ${PROMETHEUS_URL} \
  && echo "${PROMETHEUS_SHA256} /tmp/prometheus.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/prometheus.tar.gz -C /tmp/prometheus --strip-components 1

FROM $CONTAINER_REGISTRY/ubuntu:20.04

WORKDIR /prometheus

COPY --chmod=755 --from=build /tmp/prometheus/prometheus /usr/local/bin/prometheus
COPY --chmod=755 --from=build /tmp/prometheus/promtool /usr/local/bin/promtool
COPY --from=build /tmp/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
COPY --from=build /tmp/prometheus/console_libraries/ /usr/share/prometheus/console_libraries/
COPY --from=build /tmp/prometheus/consoles/ /usr/share/prometheus/consoles/
COPY --from=build /tmp/prometheus/LICENSE /LICENSE
COPY --from=build /tmp/prometheus/NOTICE /NOTICE

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && ln -s /usr/share/prometheus/console_libraries /usr/share/prometheus/consoles/ /etc/prometheus/ \
  && chown -R nobody:nogroup /etc/prometheus /prometheus

USER nobody
EXPOSE 9090
VOLUME ["/prometheus"]
ENTRYPOINT ["/usr/local/bin/prometheus"]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--storage.tsdb.retention.time=15d", \
             "--web.console.libraries=/usr/share/prometheus/console_libraries", \
             "--web.console.templates=/usr/share/prometheus/consoles" ]
