ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 as build

# metadata
LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Prometheus Alermanager."

ARG ALERTMANAGER_URL=https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-arm64.tar.gz
ARG ALERTMANAGER_SHA256=f54dd97f20b5d06517cbe83bae6333325fc26bc6595ede433f165aefb562d421

# Making use of ADD curl capability for now
# hadolint ignore=DL3020
ADD $ALERTMANAGER_URL /tmp/alertmanager.tar.gz

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/alertmanager \
  && echo "${ALERTMANAGER_SHA256} /tmp/alertmanager.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/alertmanager.tar.gz --strip-components 1 -C /tmp/alertmanager

FROM $CONTAINER_REGISTRY/ubuntu:20.04

WORKDIR /alertmanager

COPY --chmod=755 --from=build /tmp/alertmanager/amtool /usr/local/bin/amtool
COPY --chmod=755 --from=build /tmp/alertmanager/alertmanager /usr/local/bin/alertmanager
COPY --from=build /tmp/alertmanager/alertmanager.yml /etc/alertmanager/alertmanager.yml

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && chown -R nobody:nogroup /etc/alertmanager /alertmanager

USER nobody
EXPOSE 9093
VOLUME [ "/alertmanager" ]
ENTRYPOINT [ "/usr/local/bin/alertmanager" ]
CMD [ "--config.file=/etc/alertmanager/alertmanager.yml", \
      "--storage.path=/alertmanager" ]
