FROM ubuntu:20.04 AS build

ARG OP_CLI_VERSION=1.12.4

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    unzip \
  && gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22 \
  && mkdir -p /tmp/build \
  && curl -sSO https://cache.agilebits.com/dist/1P/op/pkg/v${OP_CLI_VERSION}/op_linux_arm64_v${OP_CLI_VERSION}.zip \
  && unzip -d /tmp/build op_linux_arm64_v${OP_CLI_VERSION}.zip \
  && cp /tmp/build/op /usr/local/bin/op \
  && gpg --verify /tmp/build/op.sig /usr/local/bin/op \
# tiny smoke test to ensure the binary we downloaded runs
  && op --version

FROM ubuntu:20.04

RUN useradd -m op

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    parallel \
  && rm -rf /var/lib/apt/lists/*

COPY --from=build /usr/local/bin/op /usr/local/bin/op

USER op
WORKDIR /home/op

CMD ["/bin/bash"]
