ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/polymathrobotics/python:3.8-focal

WORKDIR /code
RUN python3 -m pip install --no-cache-dir flake8==4.0.1

ENTRYPOINT ["flake8"]
CMD ["--help"]
