ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:20.04 AS build

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="1Password command-line interface."

ARG OP_CLI_VERSION=1.12.4

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    unzip \
  && gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22 \
  && mkdir -p /tmp/build \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      OP_CLI_URL='https://cache.agilebits.com/dist/1P/op2/pkg/v2.1.0/op_linux_amd64_v2.1.0.zip' \
      ;; \
    arm64) \
      OP_CLI_URL='https://cache.agilebits.com/dist/1P/op2/pkg/v2.1.0/op_linux_arm64_v2.1.0.zip' \
      ;; \
    armhf) \
      OP_CLI_URL='https://cache.agilebits.com/dist/1P/op2/pkg/v2.1.0/op_linux_arm_v2.1.0.zip' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/op_linux.zip ${OP_CLI_URL} \
  && unzip -d /tmp/build op_linux.zip \
  && cp /tmp/build/op /usr/local/bin/op \
  && gpg --verify /tmp/build/op.sig /usr/local/bin/op \
# tiny smoke test to ensure the binary we downloaded runs
  && op --version

FROM ubuntu:20.04

RUN useradd -m op

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    parallel \
    jq \
  && rm -rf /var/lib/apt/lists/*

COPY --from=build /usr/local/bin/op /usr/local/bin/op

USER op
WORKDIR /home/op

CMD ["/bin/bash"]
