# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20240808
# hadolint ignore=DL3006
FROM $BASE_IMAGE AS base

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    fdisk \
    xorriso
  # For the isohdpfx.bin file required for the legancy Ubuntu 20.04 isolinux
  # bootloader
  apt-get install -y --no-install-recommends \
    isolinux
  rm -rf /var/lib/apt/lists/*
EOF

COPY image-create.sh /app/
COPY replace-grub.sh /app/

VOLUME /data
WORKDIR /data

ENTRYPOINT [ "/app/image-create.sh" ]
