# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20240627.1

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    fdisk \
    xorriso
EOF

COPY image-create.sh /app/

VOLUME /data
WORKDIR /data

ENTRYPOINT [ "/app/image-create.sh" ]
