# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:jammy-20240808
FROM $BASE_IMAGE AS base

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    fdisk \
    xorriso
EOF

COPY image-create.sh /app/
COPY replace-grub.sh /app/

VOLUME /data
WORKDIR /data

ENTRYPOINT [ "/app/image-create.sh" ]
