# syntax=docker/dockerfile:1
# Currently there are only amd64 packages, so we install via python for now
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230425 as builder

WORKDIR /tmp

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      GLAB_URL=https://gitlab.com/gitlab-org/cli/-/releases/v1.31.0/downloads/glab_1.31.0_Linux_x86_64.deb \
      GLAB_SHA256=aa5a0b9d7ac3e18f686789e712238f91d3a00f069d4b82615bb741b8ee62d92f \
      ;; \
    arm64) \
      GLAB_URL=https://gitlab.com/gitlab-org/cli/-/releases/v1.31.0/downloads/glab_1.31.0_Linux_arm64.deb \
      GLAB_SHA256=bb31e4664345010388853df84ba5005356be78a2fab840d1c9c578a63e62d34e \
      ;; \
    armhf) \
      GLAB_URL=https://gitlab.com/gitlab-org/cli/-/releases/v1.31.0/downloads/glab_1.31.0_Linux_arm.deb \
      GLAB_SHA256=91a20a1d0a0042f184d3b2b8513ab5c3834ed0130c1bf6d1c0e3418914f9f8ee \
      ;;
    *) echo "unsupported architecture"; exit 1 ;; \
  esac 
  curl -fsSL -o glab.deb ${GLAB_URL}
  echo "${GLAB_SHA256} glab.deb" | sha256sum -c -
EOF

RUN <<EOF
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      DOCKER_URL='https://download.docker.com/linux/static/stable/x86_64/docker-24.0.2.tgz' \
      ;; \
    arm64) \
      DOCKER_URL='https://download.docker.com/linux/static/stable/aarch64/docker-24.0.2.tgz' \
      ;;
    armhf) \
      DOCKER_URL='https://download.docker.com/linux/static/stable/armhf/docker-24.0.2.tgz' \
      ;;
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o docker.tgz  ${DOCKER_URL}
  tar --extract \
		--file docker.tgz \
		--strip-components 1 \
		--directory /usr/local/bin/ \
		--no-same-owner \
		'docker/docker'
  docker --version 
EOF

ARG USERNAME=glab
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV HOME /home/$USERNAME

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230425

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="The GitLab CLI tool."

COPY --from=builder /tmp/glab.deb /tmp/glab.deb
COPY --from=builder /usr/local/bin/docker /usr/local/bin/docker
COPY entrypoint.sh /entrypoint.sh

RUN <<EOF
  groupadd --gid "$USER_GID" "$USERNAME"
  useradd --uid "$USER_UID" --gid "$USER_GID" -m "$USERNAME"
  mkdir -p "/home/$USERNAME/.config"
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    jq \
    openssh-client
  dpkg -i /tmp/glab.deb
  rm -rf /var/lib/apt/lists/*
EOF

ENTRYPOINT ["/entrypoint.sh"]
USER $USERNAME
WORKDIR $HOME
CMD [ "-h" ]

