ARG CONTAINER_REGISTRY=docker.io/polymathrobotics
FROM $CONTAINER_REGISTRY/buildpack-deps-amd64:focal-curl

# procps is very common in build systems, and is a reasonably small package
RUN apt-get update && apt-get install -y --no-install-recommends \
		bzr \
		git \
		mercurial \
		openssh-client \
		subversion \
		\
		procps \
	&& rm -rf /var/lib/apt/lists/*
